@extends('layouts.app')
@section('left-nav')
    @include('project.left-menu')
@endsection
@section('content')
    <project-table></project-table>
@endsection
@section('right-nav')
    <project-right-nav></project-right-nav>
@endsection
