@extends('layouts.app')
@section('left-nav')
    <project-left-nav></project-left-nav>
@endsection
@section('content')
    <project-table></project-table>
@endsection
@section('right-nav')
    <project-right-nav></project-right-nav>
@endsection
